name: "App Components TF template tests"
on:
  push:
    paths:
      - 'application-components/**'
  pull_request:
    paths:
      - 'application-components/**'

jobs:

  ValidateTF:
    runs-on: ubuntu-latest
    name: "Validatation (format & syntax)"
    defaults:
      run:
        working-directory: ./software-development-optimization-terraform
    steps:
    - uses: actions/checkout@v4
      name: Checkout source code

    - uses: hashicorp/setup-terraform@v3
      name: Setup Terraform

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check -recursive -diff
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate

  TFSecurityChecks:
    name: "Security Checks (checkov)"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: bridgecrewio/checkov-action@master
        with:
          directory: 'software-development-optimization-terraform/'
          quiet: true
          framework: terraform
          output_format: cli
          output_bc_ids: false
          download_external_modules: true
          skip_check: CKV_AWS_18,CKV_AWS_21,CKV_AWS_26,CKV_AWS_27,CKV_AWS_35,CKV_AWS_36,CKV_AWS_50,CKV_AWS_67,CKV_AWS_115,CKV_AWS_117,CKV_AWS_124,CKV_AWS_144,CKV_AWS_145,CKV_AWS_158,CKV_AWS_173,CKV_AWS_240,CKV_AWS_241,CKV_AWS_252,CKV_AWS_272,CKV_AWS_338,CKV2_AWS_6,CKV2_AWS_10,CKV2_AWS_61,CKV2_AWS_62,CKV_TF_1,CKV_TF_2
